name: Test Repo B (Receiver)
 
on:
  repository_dispatch:
    types: ["Triggered by API"]
    
  workflow_dispatch:
 
jobs:
  receiver:
    runs-on: ubuntu-latest
    steps:
      - name: A event received
        run: |
          echo "payload Foo '${{ github.event.client_payload.foo }}'"
